spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
    show-sql: true

---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082
