spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
    show-sql: true
